#!/bin/bash

# Configure Zsh as the login shell
# ================================

# Get dependencies
# ----------------
zsh_path=$(which zsh)

if [[ $? -ne 0 ]]; then
  printf 'zsh not found' >&2
  exit 127
fi

if [[ ! $(which sudo) ]]; then
  printf 'sudo not found' >&2
  exit 127
fi

# Add zsh to /etc/shells
# ----------------------
if ! grep -q -m 1 "^${zsh_path}$" /etc/shells; then
  sudo printf "${zsh_path}\n" >> /etc/shells

  # Exit if we can't add the shell path
  if [[ $? -ne 0 ]]; then
    printf 'entry for zsh not added to /etc/shell' >&2
    exit 128
  fi

  echo 'Added zsh to /etc/shells'
else echo 'Zsh already in /etc/shells'
fi

# Verify the config directory exists
# ----------------------------------
mkdir -p "$HOME/.config/zsh"

# Exit if the zsh config directory does not exist
if [[ -d "${HOME}"/.config/zsh ]]; then
  printf "${HOME}/.config/zsh not found" >&2
  exit 129
else echo 'Config directory found'
fi

# Set ZDOTDIR
# -----------

# We know that the zsh config directory exists at this point
if ! grep -q -m 1 '^export ZDOTDIR=' /etc/zsh/zshenv; then
  sudo printf '\nexport ZDOTDIR=$HOME/.config/zsh' >> /etc/zsh/zshenv

  # Exit if we can't set ZDOTDIR
  if [[ $? -ne 0 ]]; then
    printf 'ZDOTDIR not exported from /etc/zsh/zshenv' >&2
    exit 130
  fi

  echo 'Set ZDOTDIR'
else echo 'ZDOTDIR already set'
fi

# Set Zsh as the login shell
# --------------------------
printf "Changing the login shell to ${zsh_path}\n"
chsh -s "${zsh_path}"

