#!/bin/bash

zsh_path=$(which zsh)

if [[ $? -ne 0 ]]; then
  printf 'zsh not found' >&2
  exit 127
fi

# Add the shell path to /etc/shell
if ! grep -q "^${zsh_path}$" /etc/shells; then
  printf "${zsh_path}\n" >> /etc/shells

  # Exit if we can't add the shell path
  if [[ $? -ne 0 ]]; then
    printf 'entry for zsh not added to /etc/shell' >&2
    exit 128
  fi
fi

# Make sure the zsh config directory exists
mkdir -p "$HOME/.config/zsh"

# Exit if the zsh config directory does not exist
if [[ -d "${HOME}"/.config/zsh ]]; then
  printf "${HOME}/.config/zsh not found" >&2
  exit 129
fi

# Set ZDOTDIR (we know that the zsh config directory exists at this point)
if ! grep -q '^export ZDOTDIR=' /etc/zsh/zshenv; then
  printf '\nexport ZDOTDIR=$HOME/.config/zsh' >> /etc/zsh/zshenv

  # Exit if we can't set ZDOTDIR
  if [[ $? -ne 0 ]]; then
    printf 'ZDOTDIR not exported from /etc/zsh/zshenv' >&2
    exit 130
  fi
fi

printf "Changing the shell to ${zsh_path}\n"
chsh -s "${zsh_path}"

