#!/bin/bash

zsh_path=$(which zsh)

if [[ $? -ne 0 ]]; then
  printf 'zsh not found' >&2
  exit 127
fi

# Add the shell path to /etc/shell
if ! grep -q "^${zsh_path}$" /etc/shells; then
  printf "${zsh_path}\n" >> /etc/shells

  # Exit if we can't
  if [[ $? -ne 0 ]]; then
    printf 'could not add zsh to /etc/shell' >&2
    exit 128
  fi
fi

# Create $HOME/.config/zsh if necessary
if [[ ! -d "$HOME/.config/zsh" ]]; then
  mkdir -p "$HOME/.config/zsh"

  # Exit if we can't
  if [[ $? -ne 0 ]]; then
    printf "could not create $HOME/.config/zsh" >&2
    exit 129
  fi
fi

# Set ZDOTDIR
if [[ -d "$HOME/.config/zsh" ]] \
  && ! grep -q '^export ZDOTDIR=' /etc/zsh/zshenv; then
  printf '\nexport ZDOTDIR=$HOME/.config/zsh' >> /etc/zsh/zshenv

  # Exit if we can't
  if [[ $? -ne 0 ]]; then
    printf 'could not write ZDOTDIR to /etc/zsh/zshenv' >&2
    exit 130
  fi
fi

printf "Changing shell to ${zsh_path}\n"
chsh -s "${zsh_path}"

