#!/bin/bash
#
# Initializes the gitadd_test directory with test cases for gitadd

rm -rf ./gitadd_test
mkdir ./gitadd_test
cd ./gitadd_test
git init 1> /dev/null

printf '# Gitadd Test Repo\n\n'                        >  README.md

printf 'File name has no special characters.\n'        >  test.txt
printf 'File contains no linting issues.\n\n'          >> test.txt

printf 'File name has a space.\n'                      >  'test space_tws.txt'
printf 'File created by quoting name.\n'               >> 'test space_tws.txt'
printf 'This line has trailing spaces.   \n\n'         >> 'test space_tws.txt'

printf 'File name has a space.\n'                      >  test\ space_tab.txt
printf 'File created by escaping space in name.\n'     >> test\ space_tab.txt
printf '\tThis line contains a tab.\n\n'               >> test\ space_tab.txt

printf 'File name has surrounding whitespace.\n'       >  ' test_nbl.txt '
printf 'File created by quoting name.\n'               >> ' test_nbl.txt '
printf 'The last line of this file is not blank.\n'    >> ' test_nbl.txt '

printf 'File name has surrounding whitespace.\n'       >  ' test_mbl.txt '
printf 'File created by escaping spaces in name.\n'    >> ' test_mbl.txt '
printf 'File has multiple trailing blank lines\n\n\n'  >> ' test_mbl.txt '

printf 'File name has a backslash.\n'                  >  'test\u50_tws.txt'
printf 'File created by quoting name.\n'               >> 'test\u50_tws.txt'
printf 'This line has trailing spaces.   \n\n'         >> 'test\u50_tws.txt'

printf 'File name has special characters.\n'           >  'test!@#$%^*()-=+{}[]|;:"<>,.?\n _tab.txt'
printf 'File created by quoting name.\n'               >> 'test!@#$%^*()-=+{}[]|;:"<>,.?\n _tab.txt'
printf '\tThis line contains a tab.\n\n'               >> 'test!@#$%^*()-=+{}[]|;:"<>,.?\n _tab.txt'

printf 'File name has no special characters.\n'        >  test_tws_tab_nbl.txt
printf 'This line has trailing spaces.   \n'           >> test_tws_tab_nbl.txt
printf '\tThis line contains a tab.\n'                 >> test_tws_tab_nbl.txt
printf 'The last line of this file is not blank.'      >> test_tws_tab_nbl.txt

printf 'File name has no special characters.\n'        >  test_tws_tab_mbl.txt
printf 'This line has trailing spaces.   \n'           >> test_tws_tab_mbl.txt
printf '\tThis line contains a tab.\n'                 >> test_tws_tab_mbl.txt
printf 'File has multiple trailing blank lines\n\n\n'  >> test_tws_tab_mbl.txt

