#!/bin/bash

# Find all files, excluding files in .git directories, with underscores in
# their names and rename them, replacing the underscores with dashes
find . -type d -name .git -prune -o -type f -name '*_*' -print0 \
  | sed -zn 'p;s/_/-/g;p;' | xargs -0 -n 2 mv -iv

