#!/bin/bash

user=op
dot_repo='https://github.com/NarvinSingh/dotfiles'
cmd=''

cmd+="git clone ${dot_repo} /home/${user}/.config"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kdeglobals --group General --key fixed 'Source Code Pro,10,-1,5,50,0,0,0,0,0'"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Number 4"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Number 4"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Rows 2"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Name_1 Primary"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Name_2 Secondary"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Name_3 Web"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Desktops --key Name_4 Misc"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Windows --key BorderlessMaximizedWindows true"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Plugins --key cubeslideEnabled true"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Plugins --key blurEnabled true"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Plugins --key kwin4_effect_squashEnabled false"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group Plugins --key magiclampEnabled true"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group org.kde.kdecoration2 --key ButtonsOnLeft MXAIS"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc --group org.kde.kdecoration2 --key ButtonsOnRight H"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kglobalshortcutsrc --group kwin --key 'Switch One Desktop Down' 'Meta+J,Meta+Ctrl+Down,Switch One Desktop Down'"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kglobalshortcutsrc --group kwin --key 'Switch One Desktop to the Left' 'Meta+H,Meta+Ctrl+Left,Switch One Desktop to the Left'"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kdeglobals --group KScreen --key ScaleFactor 1.25"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/kcmfonts --group General --key forceFontDPI 120"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/touchpadxlibinputrc --group 'DLL07BE:01 06CB:7A13 Touchpad' --key naturalScroll true"
cmd+=" && kwriteconfig5 --file /home/${user}/.config/touchpadxlibinputrc --group 'DLL07BE:01 06CB:7A13 Touchpad' --key tapToClick true"

su -c "${cmd}" "${user}"

