#!/bin/bash

run () {
  local -r hostname="$1"
  local -r timezone="$2"
  local -r lang="$3"
  local -r root_passwd="$4"
  local -r user="$5"
  local -r user_passwd="$6"
  local -r dot_repo="$7"

  # Verify arguments
  if [[ "$#" -lt 4 ]]; then
    echo 'USAGE: l2-arch-install-stage-2 <hostname> <timezone> <language>'
    echo '       <root_password> <user> <user_password> [<dotfiles_repo>]'
    return 1
  fi

  # Set hostname
  echo "${hostname}" > /etc/hostname

  # Add hostname to hosts file
  {
    echo '127.0.0.1       localhost'
    echo '::1             localhost'
    echo "127.0.1.1       ${hostname}.localdomain ${hostname}"
  } >> /etc/hosts

  # Set timezone
  ln -sf /usr/share/zoneinfo/"${timezone}" /etc/localtime

  # Sync BIOS time to system time
  hwclock --systohc

  # Generate locale
  local -r lang_pattern="$(echo "${lang}" | sed 's/[]\/$*.^[]/\\&/g')"
  sed -i "s/^#\(${lang_pattern}\)/\1/" /etc/locale.gen
  locale-gen

  # Persist locale
  echo "LANG=${lang}" > /etc/locale.conf

  # Create swapfile
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # Install packages
  pacman -Syyy
  pacman -S --needed \
    grub \
    efibootmgr \
    intel-ucode \
    mesa \
    nvidia \
    nvidia-prime \
    iwd \
    dhcpcd \
    base-devel \
    man-db \
    zsh \
    vim \
    git \
    xorg-server \
    plasma \
    konsole \
    dolphin \
    firefox

  # Configure bootloader
  grub-install --target=x86_64-efi --bootloader-id=grub_uefi \
    --efi-directory=/boot/EFI --recheck
  grub-mkconfig -o /boot/grub/grub.cfg

  # Enable services
  systemctl enable iwd dhcpcd

  # Set root password
  printf '%s\n%s\n' "${root_passwd}" "${root_passwd}" | passwd

  # Global customization
  sed -i 's/^#\s*\(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers
  printf 'export TERM=xterm-256color\n' >> /etc/zsh/zshenv
  # ${HOME} will be expanded when zshenv is ran
  # shellcheck disable=SC2016
  printf 'export ZDOTDIR=${HOME}/.config/zsh\n' >> /etc/zsh/zshenv
  printf 'export TERM=xterm-256color\n' >> /etc/bash.bashrc
  # ${HOME} will be expanded when bash.bashrc is ran
  # shellcheck disable=SC2016
  printf 'source ${HOME}/.config/bash/bashrc\n' >> /etc/bash.bashrc
  rm /etc/skel/.bashrc

  # Create user
  useradd -m -s "$(which zsh)" -g users -G wheel "${user}"
  printf '%s\n%s\n' "${user_passwd}" "${user_passwd}" | passwd "${user}"

  # User customization
  if [[ -n "${dot_repo}" ]]; then
    local cmd=''

    # Clone dotfiles repo
    cmd+="git clone ${dot_repo} /home/${user}/.config"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kdeglobals"

    # Fixed font
    cmd+=" --group General --key fixed 'Source Code Pro,10,-1,5,50,0,0,0,0,0'"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"

    # 4 desktops in 2 rows
    cmd+=" --group Desktops --key Number 4"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Desktops --key Rows 2"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Desktops --key Name_1 Primary"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Desktops --key Name_2 Secondary"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Desktops --key Name_3 Web"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Desktops --key Name_4 Misc"

    # Borderless maximized windows
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Windows --key BorderlessMaximizedWindows true"

    # Desktop switching cube slide animation
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Plugins --key cubeslideEnabled true"

    # Blur background behind transparent windows
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Plugins --key blurEnabled true"

    # Disable squash effect and enable magic lamp effect for minimized windows
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Plugins --key kwin4_effect_squashEnabled false"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group Plugins --key magiclampEnabled true"

    # Window title bar buttons on the left
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group org.kde.kdecoration2 --key ButtonsOnLeft MXAIS"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kwinrc"
    cmd+=" --group org.kde.kdecoration2 --key ButtonsOnRight H"

    # Desktop switching keyboard shortcuts
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kglobalshortcutsrc"
    cmd+=" --group kwin --key 'Switch One Desktop Down'"
    cmd+=" 'Meta+J,Meta+Ctrl+Down,Switch One Desktop Down'"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kglobalshortcutsrc"
    cmd+=" --group kwin --key 'Switch One Desktop to the Left'"
    cmd+=" 'Meta+H,Meta+Ctrl+Left,Switch One Desktop to the Left'"

    # Resolution specific: wallpaper
    # This isn't working
    ## cmd+=" && kwriteconfig5"
    ## cmd+=" --file /home/${user}/.config/plasma-org.kde.plasma.desktop-appletsrc"
    ## cmd+=" --group Containments --group 1 --group Wallpaper"
    ## cmd+=" --group org.kde.image --group General --key Image"
    ## cmd+=" file:///usr/share/wallpapers/OneStandsOut/contents/images/1920x1080.jpg"

    # Machine specific: scale display 125% and increase font DPI to 120
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kdeglobals"
    cmd+=" --group KScreen --key ScaleFactor 1.25"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/kcmfonts"
    cmd+=" --group General --key forceFontDPI 120"

    # Machine specific: enable tap to click and natural scrolling
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/touchpadxlibinputrc"
    cmd+=" --group 'DLL07BE:01 06CB:7A13 Touchpad' --key tapToClick true"
    cmd+=" && kwriteconfig5 --file /home/${user}/.config/touchpadxlibinputrc"
    cmd+=" --group 'DLL07BE:01 06CB:7A13 Touchpad' --key naturalScroll true"
    su -c "${cmd}" "${user}"
  fi
}

run "$@"

