#!/bin/bash

run () {
  local -r hostname="$1"
  local -r timezone="$2"
  local -r lang="$3"
  local -r root_passwd="$4"
  local -r user="$5"
  local -r user_passwd="$6"
  local -r dot_repo="$7"

  # Verify arguments
  if [[ "$#" -lt 4 ]]; then
    echo 'USAGE: l2-arch-install-stage-2 <hostname> <timezone> <language>'
    echo '       <root_password> <user> <user_password> [<dotfiles_repo>]'
    return 1
  fi

  # Set hostname
  echo "${hostname}" > /etc/hostname

  # Add hostname to hosts file
  {
    echo '127.0.0.1       localhost'
    echo '::1             localhost'
    echo "127.0.1.1       ${hostname}.localdomain ${hostname}"
  } >> /etc/hosts

  # Set timezone
  ln -sf /usr/share/zoneinfo/"${timezone}" /etc/localtime

  # Sync BIOS time to system time
  hwclock --systohc

  # Generate locale
  local -r lang_pattern="$(echo "${lang}" | sed 's/[]\/$*.^[]/\\&/g')"
  sed -i "s/^#\(${lang_pattern}\)/\1/" /etc/locale.gen
  locale-gen

  # Persist locale
  echo "LANG=${lang}" > /etc/locale.conf

  # Create swapfile
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # Install packages
  pacman -Syyy
  pacman -S --needed \
    intel-ucode \
    mesa \
    nvidia \
    nvidia-prime \
    iwd \
    dhcpcd \
    zsh \
    vim \
    git

  # Configure bootloader
  bootctl install
  {
    echo 'default      arch.conf'
    echo 'timeout      4'
    echo 'console-mode max'
    echo 'editor       no'
  } > /boot/loader/loader.conf
  {
    echo 'title   Arch Linux'
    echo 'linux   /vmlinuz-linux'
    echo 'initrd  /intel-ucode.img'
    echo 'initrd  /initramfs-linux.img'
    local -r part="$(mount | grep -m 1 'on / ' | cut -d ' ' -f 1)"
    local -r uuid="$(blkid "${part}" \
      | grep -o ' UUID="[0-9a-f-]*' | cut -c 8-)"
    echo "options root=UUID=${uuid} rw"
  } > /boot/loader/entries/arch.conf
  bootctl update

  # Enable services
  systemctl enable iwd dhcpcd

  # Set root password
  printf '%s\n%s\n' "${root_passwd}" "${root_passwd}" | passwd

  # Global customization
  sed -i 's/^#\s*\(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers
  printf 'export TERM=xterm-256color\n' >> /etc/zsh/zshenv
  # ${HOME} will be expanded when zshenv is ran
  # shellcheck disable=SC2016
  printf 'export ZDOTDIR=${HOME}/.config/zsh\n' >> /etc/zsh/zshenv
  printf 'export TERM=xterm-256color\n' >> /etc/bash.bashrc
  # ${HOME} will be expanded when bash.bashrc is ran
  # shellcheck disable=SC2016
  printf 'source ${HOME}/.config/bash/bashrc\n' >> /etc/bash.bashrc
  rm /etc/skel/.bashrc

  # Create user
  useradd -m -s "$(which zsh)" -g users -G wheel "${user}"
  printf '%s\n%s\n' "${user_passwd}" "${user_passwd}" | passwd "${user}"

  # User customization
  if [[ -n "${dot_repo}" ]]; then
    local cmd=''

    # Clone dotfiles repo
    cmd+="git clone ${dot_repo} /home/${user}/.config"
    su -c "${cmd}" "${user}"
  fi
}

run "$@"

