#!/bin/bash

run () {
  local -r hostname="$1"
  local -r timezone="$2"
  local -r lang="$3"
  local -r root_passwd="$4"
  local -r user="$5"
  local -r user_passwd="$6"
  local -r dot_repo="$7"

  # Verify arguments
  if [[ "$#" -lt 4 ]]; then
    echo 'USAGE: l2-arch-install-stage-2 <hostname> <timezone> <language>'
    echo '       <root_password> <user> <user_password> [<dotfiles_repo>]'
    return 1
  fi

  # Set hostname
  echo "${hostname}" > /etc/hostname

  # Add hostname to hosts file
  {
    echo '127.0.0.1       localhost'
    echo '::1             localhost'
    echo "127.0.1.1       ${hostname}.localdomain ${hostname}"
  } >> /etc/hosts

  # Set timezone
  ln -sf /usr/share/zoneinfo/"${timezone}" /etc/localtime

  # Sync BIOS time to system time
  hwclock --systohc

  # Generate locale
  local -r lang_pattern="$(echo "${lang}" | sed 's/[]\/$*.^[]/\\&/g')"
  sed -i "s/^#\(${lang_pattern}\)/\1/" /etc/locale.gen
  locale-gen

  # Persist locale
  echo "LANG=${lang}" > /etc/locale.conf

  # Create swapfile
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  echo '/swapfile none swap sw 0 0' >> /etc/fstab

  # Install packages
  pacman -Syyy
  pacman -S --needed \
    grub \
    efibootmgr \
    intel-ucode \
    mesa \
    nvidia \
    nvidia-utils \
    iwd \
    dhcpcd \
    sudo \
    which \
    man-db \
    zsh \
    vim \
    xorg-server \
    plasma \
    konsole \
    dolphin \
    firefox

  # Configure bootloader
  grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
  grub-mkconfig -o /boot/grub/grub.cfg

  # Enable services
  systemctl enable iwd dhcpcd sddm

  # Set root password
  printf '%s\n%s\n' "${root_passwd}" "${root_passwd}" | passwd

  # Global customization
  sed -i 's/^#\s*\(%wheel ALL=(ALL) ALL\)/\1/' /etc/sudoers
  printf 'export TERM=xterm-256color\n' >> /etc/zsh/zshenv
  # ${HOME} will be expanded when zshenv is ran
  # shellcheck disable=SC2016
  printf 'export ZDOTDIR=${HOME}/.config/zsh\n' >> /etc/zsh/zshenv
  printf 'export TERM=xterm-256color\n' >> /etc/bash.bashrc
  # ${HOME} will be expanded when bash.bashrc is ran
  # shellcheck disable=SC2016
  printf 'source ${HOME}/.config/bash/bashrc\n' >> /etc/bash.bashrc
  rm /etc/skel/.bashrc

  # Create user
  useradd -m -s "$(which zsh)" -g users -G wheel "${user}"
  printf '%s\n%s\n' "${user_passwd}" "${user_passwd}" | passwd "${user}"

  # User customization
  if [[ -n "${dot_repo}" ]]; then
    pacman -S --needed git
    su -c "git clone ${dot_repo} /home/${user}/.config" "${user}"
  fi
}

run "$@"

