#!/bin/bash

run () {
  {
    echo 'default      arch.conf'
    echo 'timeout      4'
    echo 'console-mode max'
    echo 'editor       no'
  } > ./loader.conf
  {
    echo 'title   Arch Linux'
    echo 'linux   /vmlinuz-linux'
    echo 'initrd  /intel-ucode.img'
    echo 'initrd  /initramfs-linux.img'
    local -r part="$(mount | grep -m 1 'on / ' | cut -d ' ' -f 1)"
    local -r uuid="$(blkid "${part}" \
      | grep -o ' UUID="[0-9a-f-]*' | cut -c 8-)"
    echo "options root=UUID=${uuid} rw"
  } > ./arch.conf
}

run

